# .gitlab-ci.yml

# voor test alleen, wordt aan gewerkt door Beni
image: mcr.microsoft.com/playwright:v1.40.1-jammy
stages:
  - test

default:
  cache: &default_cache
    policy: pull
    key:
      files:
        - package*.json
    paths:
      - .npm/


update-cache:
  stage: .pre
  script:
    - npm clean-install --cache .npm --prefer-offline -D
  cache:
    <<: *default_cache
    policy: pull-push
  rules:
    - changes:
        - package*.json
    - if: $FORCE_CACHE_UPDATE == "true"

performance:on-schedule:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: test
  script:
    # - mvn clean test -D"RUN_VAR=${RUN_VAR}"
    - npm clean-install --cache .npm --prefer-offline -D
    - npx --cache .npm bddgen
    # - npx --cache .npm playwright test performance
    # - npm run update-screenshots
    - npm run performance
  after_script:
    - bash fix-junit-urls.sh
  parallel:
    matrix:
      - PROJECT: ['chromium']
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - junit-results*.xml
    reports:
      junit: junit-results.xml
    expire_in: 7 days

playwright:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  stage: test
  script:
    - npm clean-install --cache .npm --prefer-offline -D
    - npx --cache .npm bddgen
    # - npx --cache .npm playwright test performance
    # - npm run update-screenshots
    - npm run landing
  after_script:
    - bash fix-junit-urls.sh
  parallel:
    matrix:
      - PROJECT: ['chromium']
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - junit-results*.xml
    reports:
      junit: junit-results.xml
    expire_in: 30 days
